#!/bin/bash
#this first line is to take in user input so the terminal
read your_command
#next we will update the package lists 
sudo apt-get update
#now we can upgrade our system
sudo apt-get upgrade
#now we do the actual tree shaking by running apt auto-clean
sudo apt-get auto-clean
#finally you run your custom install command
sudo $your_command 
